### ISSUE TITLE
FastINRTrainer not Found

### ISSUE THREAD

**Issue by danielkaifeng** [universome/inr-gan#3]
currently the code may not be used because of module rename, could you please solve this?

**Comment by universome** [comment]
Oh, I am sorry. I have updated the `README.md` file, and it now includes the proper command to run the code:
```
CUDA_VISIBLE_DEVICES=0 python src/run.py -c configs/inr-gan.yml --config.dataset lsun_256
```

**Comment by danielkaifeng** [comment]
hi, universome, but there is still no fast_inr_trainer in folder src/trainers, can you run the command locally?  could you check where this file is?

```
Traceback (most recent call last):
  File "src/run.py", line 7, in <module>
    from src.trainers import GANTrainer, StaticINRsTrainer
  File "./src/trainers/__init__.py", line 1, in <module>
    from .fast_inr_trainer import FastINRTrainer
ModuleNotFoundError: No module named 'src.trainers.fast_inr_trainer'
```

**Comment by danielkaifeng** [comment]
I modify the code and use alternative trainer module, but the config file seems miss lots of params:
```
  File "./src/trainers/gan_trainer.py", line 51, in build_model
    return INRGAN(self.config)
  File "./src/models/inr_gan.py", line 29, in __init__
    self.generator = INRGenerator(config)
  File "./src/models/inr_gan.py", line 47, in __init__
    self.init_inr()
  File "./src/models/inr_gan.py", line 54, in init_inr
    self.inr = FourierINRs(self.config)
  File "./src/models/inrs/inrs.py", line 44, in __init__
    self.init_model()
  File "./src/models/inrs/inrs.py", line 227, in init_model
    if self.config.hp.inr.residual:
AttributeError: 'Config' object has no attribute 'residual'
```
